# Generated by Django 3.1 on 2020-10-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_communityjoinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityjoinrequest',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='accept  the user in the community'),
        ),
    ]
