# Generated by Django 3.1 on 2020-10-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_eventjoinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventjoinrequest',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='join request in accepted'),
        ),
    ]
