# Generated by Django 3.1 on 2020-10-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_eventjoinrequest_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='event accepted'),
        ),
    ]
